### PR TITLE
Map fixes for some rogue maps

### PR DESCRIPTION
**Pull request by BjossiAlfreds**
This PR addresses map bugs reported in https://github.com/yquake2/yquake2/issues/684 as well as some new ones I found (see documentation in the ent files for the details).

### CODE REVIEW

**Comment by Froyd1** [comment]
Thanks for all these fixes. Just some questions I want to ask, when will the next full version of Yamagi be out, so all these fixes will come with it? Also, was all six enemies found and fixed in the Waterfront Storage level, since it has the most bugs in it?

**Comment by BjossiAlfreds** [comment]
Only @Yamagi knows how the release package will look like, I don't know if the ent files will be part of it, but they will be mentioned in the docs and how to download and use them.

As for rware2. Only 1 of the 4 enemies you reported was a map bug. The guy with the really big negative z number had fallen through the floor, which seems more of a code bug (specifically the collision detection system). The other 2 guys had x and y numbers that looked like they had already moved, so they were either dead bodies or stragglers running around. The discrepancy with the monster count is interesting though, maybe I'll investigate that more closely some time - how you can have at least 2 monsters left to kill when in fact everything is dead.

**Comment by Froyd1** [comment]
I guess I will wait for next version for the fixes to be included. Yeah, do look into that level, and let me know about the monster count. When the next version does come out, I will replay this, and let you know if all the enemies are killed. If not, I will post another bug report.

**Comment by BjossiAlfreds** [comment]
You don't need to test again, I just figured out the problem. rware1 and rware2 have entities that killtarget monsters. killtarget actually deletes an entity instantly, so the normal monster death code is skipped. To some degree this may be map bugs but I think a code workaround is in order regardless.

So basically, some trigger event you activate deletes monsters. There are 5 of them in rware2 and 1 in rware1. The other levels seem to be free of this problem.

**Comment by Froyd1** [comment]
I wonder if it's the goal, when you disguise yourself as a strogg or is it something else? This is so confusing though, should I wait for a proper fix? Thanks for looking further into this mess, of that level.

**Comment by BjossiAlfreds** [comment]
It's the tank commander you kill with those lasers. If he dies, then the 5 gunners won't appear. Such a weird, random detail to put in a unit of maps. Had no idea this was a thing.

**Comment by BjossiAlfreds** [comment]
I just pushed a small code change that updates killcounter when a living monster is killtargeted.

It was actually tricky to identify monster entities because they don't really have a unique identity. I ended up just checking for a checkattack function pointer or the turret_driver (he doesn't have that but counts as a monster). Then there are further checks for ai_good_guy and ai_do_not_count aiflags, and of course make sure the deadflag isn't set.

**Comment by Froyd1** [comment]
Thanks, looking forward to the next version with these fixes. :)

**Comment by Yamagi** [comment]
> when will the next full version of Yamagi be out

The next version  will be 8.00 and include the Vulkan renderer. There's still one blocker left in yquake2/yquake2#647. After that one is solved we'll do a release candidate.

> Only @Yamagi knows how the release package will look like

I haven't decided upon that. Maybe with another testbuild sometimes next week, depend on my day job.

**Pull request merged**
