### PR TITLE
Forcing proper native arch build on darwin mainly due to arm64

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by Yamagi** [comment]
This will break savegames in all cases, where the arch string changes. I think that's okay, since MacOS is community supported, there aren't that many M1 Macs out there and it's only the addons. Should I merge this or does someone insist on bumping the savegame version and implementing fallback magic? Bumping the version isn't that nice either, it breaks forward compatibility.

**Comment by DanielGibson** [comment]
maybe we should make a distinction between arm and arm64, regardless of Mac or not?

**Comment by Yamagi** [comment]
At least on FreeBSD and Linux `uname -m` gives `aarch64` on ARM64. `s/^arm.*/arm/'` is there to normalize all these 32 bit ARM dialects to just `arm`.

**Comment by DanielGibson** [comment]
While I still think that it might be nice to tell apart arm and arm64 on platforms where both exist, is this really relevant for macOS? I mean, 32bit ARM isn't really a thing there, right?

**Comment by Yamagi** [comment]
MacOS an OpenBSD are different to FreeBSD and Linux, `uname -m` gives `arm64`. What about adding `s/arm64/aarch64/'`? That would normalize all ARM64 platform to `aarch64`. It would still break savegames, but I thing only M1 mac are slightly relevant here. OpenBSD hasn't suitable GPU drivers for it's ARM port.

**Comment by Yamagi** [comment]
I'm merging this and the other pull requests. It'll bring the addons and Quake II itself up to par. The only functional change is, that under MacOS on ARM the addons are build with another arch string. That will break savegame compatibility on M1 Macs. The very users playing the addons on an M1 Mac can postpone the update until they finished their playthrough. Or they can hexedit the savegame, changing the `arm` header field to `arm64`. There's a lot of padding (set to 0), so overwriting two 0 bytes isn't a problem.

And I'll shortly push another commit which normalizes arm64 to aarch64 on everything that isn't MacOS or Windows. It will break savegame compatibility in some corner cases, the most prominent is OpenBSD on ARM64. Since OpenBSD hasn't GPU drivers for any ARM systems, this shouldn't cause problems.

**Pull request merged**
